DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"
DEFINE TABLESPACE_INDEX_NAME = &&USER_NAME._INDEX

SET SERVEROUTPUT ON

CREATE TABLE customer ( 
  customer_id NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ,
  name VARCHAR(500) NOT NULL,
  address VARCHAR(500) NOT NULL,
  CONSTRAINT customer_pk 
    PRIMARY KEY (customer_id)
  USING INDEX (
      CREATE UNIQUE INDEX pk_customer ON customer(customer_id ASC)
	  TABLESPACE &&TABLESPACE_INDEX_NAME
  )
)
TABLESPACE &&TABLESPACE_NAME;

COMMENT ON COLUMN customer.customer_id IS 'Уникальный идентификатор заказчика';
COMMENT ON COLUMN customer.name IS 'Имя заказчика';
COMMENT ON COLUMN customer.address IS 'Адресс заказчика';

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX_NAME