DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = "&&USER_NAME._DATA"

CREATE TABLE GoogleExcelTable ( 
  BATCH_NUMBER NUMBER NOT NULL,
  BATCH_STATUS VARCHAR(500),
  CUSTOMER_NAME VARCHAR(500),
  ADDRESS VARCHAR(500),
  TRANSPORT VARCHAR(500),
  BOX_WEIGHT NUMBER(10,5),
  BOX_TYPE VARCHAR(500),
  BOX_PRICE NUMBER(10,5),
  BOX_COUNT NUMBER,
  PRODUCT_NAME VARCHAR(500),
  PRODUCT_PRICE NUMBER(10,5),
  PRODUCT_WEIGHT NUMBER(10,5),
  SHELF_LIFE NUMBER,
  FOOD_ENERGY NUMBER(10,5),
  PROTEIN NUMBER(10,5),
  FATS NUMBER(10,5),
  CARBONOHYDRATES NUMBER(10,5),
  COCOA NUMBER(10,5),
  CONSTRAINT batch_pk 
    PRIMARY KEY (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA)
)
TABLESPACE &&TABLESPACE_NAME;

Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','10','Для транспортировки','957.5','5','Горький шоколад с начинкой из абрикосового пюре','3.83','0.2','12','1830','3','19','63','56');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','30','Для транспортировки','10341','18','Горький шоколад с начинкой из пюре черной смородины','3.83','0.2','12','1830','3','19','63','56');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','10','Для транспортировки','2625','21','Молочный шоколад с изысканной начинкой с клубничным пюре и молочным кремом','1.25','0.1','12','2160','3.5','29','60','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','20','Для транспортировки','14352','23','Нежный молочный шоколад с ароматными кусочками свежей клубники и воздушным рисом','3.12','0.1','12','2260','5','33','56','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','10','Для транспортировки','3267','11','Подарочный набор шоколада «Беларусь синеокая»','5.94','0.2','12','2310','5.5','36','52','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','10','Для транспортировки','4740','30','Какао-порошок "Коммунарка"','2.37','0.15','12','1373','25.6','12','29.6','100');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','5','Для продажи','501.25','25','Карамель леденцовая «Зубастики» кола-ла','4.01','1','12','1670','0','0.1','98','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','10','Для продажи','862.4','22','Карамель с молочной начинкой со вкусом пломбира','3.92','1','12','1616','0.4','1.1','92.6','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','7.7','Для транспортировки','6711','30','Maya Legends','22.37','0.77','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('1','Формируется','Евроопт','г. Минск, ул. Слободская д.131, пом. 1','Свой','3.85','Для транспортировки','5132','40','Maya Legends','12.83','0.38','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','10','Для транспортировки','4213','22','Горький шоколад с начинкой из абрикосового пюре','3.83','0.2','12','1830','3','19','63','56');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','7.7','Для транспортировки','4921.4','22','Maya Legends','22.37','0.77','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','3.85','Для транспортировки','2282.6','22','Maya Legends','12.83','0.38','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','30','Для транспортировки','12639','22','Горький шоколад с начинкой из пюре черной смородины','3.83','0.2','12','1830','3','19','63','56');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','10','Для транспортировки','2750','22','Молочный шоколад с изысканной начинкой с клубничным пюре и молочным кремом','1.25','0.1','12','2160','3.5','29','60','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','20','Для транспортировки','13728','22','Нежный молочный шоколад с ароматными кусочками свежей клубники и воздушным рисом','3.12','0.1','12','2260','5','33','56','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','10','Для транспортировки','6534','22','Подарочный набор шоколада «Беларусь синеокая»','5.94','0.2','12','2310','5.5','36','52','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','10','Для транспортировки','3476','22','Какао-порошок "Коммунарка"','2.37','0.15','12','1373','25.6','12','29.6','100');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','5','Для продажи','441.1','22','Карамель леденцовая «Зубастики» кола-ла','4.01','1','12','1670','0','0.1','98','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('2','Сформировано','Евроопт','г. Минск, ул. Слободская д.133, пом. 1','Арендованный','10','Для продажи','862.4','22','Карамель с молочной начинкой со вкусом пломбира','3.92','1','12','1616','0.4','1.1','92.6','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','10','Для транспортировки','2298','12','Горький шоколад с начинкой из абрикосового пюре','3.83','0.2','12','1830','3','19','63','56');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','7.7','Для транспортировки','7158.4','32','Maya Legends','22.37','0.77','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','3.85','Для транспортировки','5645.2','44','Maya Legends','12.83','0.38','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','10','Для транспортировки','2625','21','Молочный шоколад с изысканной начинкой с клубничным пюре и молочным кремом','1.25','0.1','12','2160','3.5','29','60','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','10','Для транспортировки','6534','22','Подарочный набор шоколада «Беларусь синеокая»','5.94','0.2','12','2310','5.5','36','52','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','20','Для транспортировки','4992','8','Нежный молочный шоколад с ароматными кусочками свежей клубники и воздушным рисом','3.12','0.1','12','2260','5','33','56','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('3','Доставляется','Корона','г. Минск, ул. Денисовская, 8','Свой','10','Для продажи','862.4','22','Карамель с молочной начинкой со вкусом пломбира','3.92','1','12','1616','0.4','1.1','92.6','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','20','Для транспортировки','14352','23','Нежный молочный шоколад с ароматными кусочками свежей клубники и воздушным рисом','3.12','0.1','12','2260','5','33','56','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','10','Для транспортировки','3267','11','Подарочный набор шоколада «Беларусь синеокая»','5.94','0.2','12','2310','5.5','36','52','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','10','Для транспортировки','4741','30','Какао-порошок "Коммунарка"','2.37','0.15','12','1373','25.6','12','29.6','100');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','30','Для транспортировки','10341','18','Горький шоколад с начинкой из пюре черной смородины','3.83','0.2','12','1830','3','19','63','56');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','10','Для продажи','862.4','22','Карамель с молочной начинкой со вкусом пломбира','3.92','1','12','1616','0.4','1.1','92.6','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','3.85','Для транспортировки','5645.2','44','Maya Legends','12.83','0.38','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','7.7','Для транспортировки','4250.3','19','Maya Legends','22.37','0.77','12','2282','5.9','32.9','55.9','0');
Insert into GoogleExcelTable (BATCH_NUMBER,BATCH_STATUS,CUSTOMER_NAME,ADDRESS,TRANSPORT,BOX_WEIGHT,BOX_TYPE,BOX_PRICE,BOX_COUNT,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_WEIGHT,SHELF_LIFE,FOOD_ENERGY,PROTEIN,FATS,CARBONOHYDRATES,COCOA) values ('4','Доставлено','Корона','г. Борисов, ул. III Интернационала, 5','Арендованный','10','Для транспортировки','11490','60','Горький шоколад с начинкой из абрикосового пюре','3.83','0.2','12','1830','3','19','63','56');

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME
UNDEFINE TABLESPACE_INDEX_NAME