SET TIME ON
SET TIMING ON
SPOOL DROP_SCHEMA.LOG

DEFINE USER_NAME_ = &&1
SET SERVEROUTPUT ON

PROMPT
PROMPT Username: &&USER_NAME_
PROMPT
PROMPT Dropping user
@drop_user.sql &&USER_NAME_
PROMPT
PROMPT Dropping tablespace
@drop_tablespace.sql &&USER_NAME_
PROMPT

SET SERVEROUTPUT OFF
UNDEFINE USER_NAME_

SPOOL OFF