DEFINE USER_NAME = &&1
DEFINE TBS_LOCATION = &&2
DEFINE TABLESPACE_NAME = '&&USER_NAME._DATA'
DEFINE DATA_FILENAME =  '&&TBS_LOCATION&&TABLESPACE_NAME..dbf'

PROMPT &&TABLESPACE_NAME
PROMPT &&DATA_FILENAME

CREATE TABLESPACE  &&TABLESPACE_NAME
    DATAFILE 
        '&&DATA_FILENAME' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 10G;
		
UNDEFINE USER_NAME;
UNDEFINE TBS_LOCATION;
UNDEFINE TABLESPACE_NAME;
UNDEFINE DATA_FILENAME;