SET TIME ON
SET TIMING ON
SPOOL INSTALL_SCHEMA.LOG

DEFINE USER_NAME_ = &&1
DEFINE TBS_LOCATION_ =  &&2

SET SERVEROUTPUT ON

PROMPT
PROMPT Username: &&USER_NAME_
PROMPT Path: &&TBS_LOCATION_
PROMPT
PROMPT Calling data and index creating
@create_tablespace.sql &&USER_NAME_ &&TBS_LOCATION_
PROMPT
PROMPT Calling user creation
@create_user.sql &&USER_NAME_
PROMPT
PROMPT Giving grants to user
@grants.sql &&USER_NAME_
PROMPT

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME_
UNDEFINE TBS_LOCATION_

SPOOL OFF